@extends('layouts.app')
@section('title', 'Select Seats — ' . $show->movie->title)

@section('content')

{{-- Movie Info Bar --}}
<div style="background:var(--surface-1); border-bottom:1px solid var(--border-1); padding:1rem 0; position:sticky; top:64px; z-index:50;">
    <div class="container">
        <div style="display:flex; align-items:center; justify-content:space-between; flex-wrap:wrap; gap:1rem;">
            <div style="display:flex; align-items:center; gap:14px;">
                <a href="{{ route('movies.show', $show->movie_id) }}"
                   style="color:var(--text-3); font-size:13px; text-decoration:none; display:flex; align-items:center; gap:5px;"
                   onmouseover="this.style.color='#fff'" onmouseout="this.style.color='var(--text-3)'">
                    ← Back
                </a>
                <div style="width:1px; height:20px; background:var(--border-2);"></div>
                <div>
                    <div style="font-size:15px; font-weight:700;">{{ $show->movie->title }}</div>
                    <div style="font-size:12px; color:var(--text-3);">
                        {{ $show->theater->name }} &bull;
                        {{ $show->show_date->format('D, d M Y') }} &bull;
                        {{ \Carbon\Carbon::parse($show->show_time)->format('h:i A') }}
                    </div>
                </div>
            </div>
            <div style="display:flex; gap:8px; flex-wrap:wrap;">
                <span style="background:rgba(239,159,39,.1); border:1px solid rgba(239,159,39,.3); color:#EF9F27; font-size:11px; font-weight:700; padding:4px 12px; border-radius:5px;">Gold: Rs.{{ number_format($show->gold_price) }}</span>
                <span style="background:rgba(55,138,221,.1); border:1px solid rgba(55,138,221,.3); color:#378ADD; font-size:11px; font-weight:700; padding:4px 12px; border-radius:5px;">Platinum: Rs.{{ number_format($show->platinum_price) }}</span>
                <span style="background:rgba(127,119,221,.1); border:1px solid rgba(127,119,221,.3); color:#7F77DD; font-size:11px; font-weight:700; padding:4px 12px; border-radius:5px;">Box: Rs.{{ number_format($show->box_price) }}</span>
            </div>
        </div>
    </div>
</div>

<div class="container" style="padding-top:2rem; padding-bottom:3rem;">

    {{-- Class info cards --}}
    <div style="display:grid; grid-template-columns:repeat(3,1fr); gap:1rem; margin-bottom:2rem;">
        <div style="background:#0d0800; border:1px solid #2a1500; border-radius:var(--radius-md); padding:1rem; text-align:center;">
            <div style="font-size:12px; font-weight:800; color:#EF9F27; letter-spacing:.08em; text-transform:uppercase; margin-bottom:4px;">Gold Class</div>
            <div style="font-size:20px; font-weight:900; color:#fff;">Rs.{{ number_format($show->gold_price) }}</div>
            <div style="font-size:11px; color:var(--text-3); margin-top:3px;">Rows F – L</div>
        </div>
        <div style="background:#00101a; border:1px solid #0c447c; border-radius:var(--radius-md); padding:1rem; text-align:center;">
            <div style="font-size:12px; font-weight:800; color:#378ADD; letter-spacing:.08em; text-transform:uppercase; margin-bottom:4px;">Platinum Class</div>
            <div style="font-size:20px; font-weight:900; color:#fff;">Rs.{{ number_format($show->platinum_price) }}</div>
            <div style="font-size:11px; color:var(--text-3); margin-top:3px;">Rows C – E</div>
        </div>
        <div style="background:#100010; border:1px solid #3C3489; border-radius:var(--radius-md); padding:1rem; text-align:center;">
            <div style="font-size:12px; font-weight:800; color:#7F77DD; letter-spacing:.08em; text-transform:uppercase; margin-bottom:4px;">Box Class</div>
            <div style="font-size:20px; font-weight:900; color:#fff;">Rs.{{ number_format($show->box_price) }}</div>
            <div style="font-size:11px; color:var(--text-3); margin-top:3px;">Rows A – B</div>
        </div>
    </div>

    {{-- Seat Map --}}
    <div style="background:var(--surface-2); border:1px solid var(--border-1); border-radius:var(--radius-lg); padding:2rem;">

        {{-- Screen --}}
        <div style="text-align:center; margin-bottom:2.5rem;">
            <div style="width:60%; margin:0 auto; height:7px; background:linear-gradient(90deg,transparent,var(--red) 30%,var(--orange) 50%,var(--red) 70%,transparent); border-radius:0 0 50% 50%;"></div>
            <div style="font-size:10px; letter-spacing:.2em; color:var(--text-4); margin-top:10px; text-transform:uppercase; font-weight:600;">SCREEN</div>
        </div>

        {{-- Hall --}}
        <div style="overflow-x:auto; padding-bottom:10px;">
            <div id="seatHall" style="min-width:fit-content; margin:0 auto;">
                {{-- Generated by JS --}}
            </div>
        </div>

        {{-- Legend --}}
        <div style="display:flex; flex-wrap:wrap; gap:16px; justify-content:center; margin-top:1.5rem; padding-top:1.5rem; border-top:1px solid var(--border-1);">
            @foreach([
                ['#1a1000','#633806','Gold Available'],
                ['#00101a','#0c447c','Platinum Available'],
                ['#100010','#3C3489','Box Available'],
                ['var(--red)','#ff5544','Selected'],
                ['rgba(30,30,30,.4)','#2a2a2a','Booked'],
            ] as $l)
            <div style="display:flex; align-items:center; gap:7px; font-size:12px; color:var(--text-2);">
                <div style="width:16px; height:16px; border-radius:4px 4px 2px 2px; background:{{ $l[0] }}; border:1px solid {{ $l[1] }};"></div>
                {{ $l[2] }}
            </div>
            @endforeach
        </div>
    </div>

    {{-- Booking Summary Bar --}}
    <div id="summaryBar" style="position:fixed; bottom:0; left:0; right:0; background:rgba(10,10,10,.96); border-top:1px solid var(--border-2); backdrop-filter:blur(12px); padding:1rem 1.5rem; z-index:100; display:flex; align-items:center; justify-content:space-between; flex-wrap:wrap; gap:1rem; transform:translateY(100%); transition:transform .35s ease;">
        <div>
            <div style="font-size:12px; color:var(--text-3); margin-bottom:4px;">Selected Seats</div>
            <div id="selectedDisplay" style="font-size:14px; font-weight:700; color:#fff; font-family:var(--font-mono);">None</div>
        </div>
        <div style="display:flex; align-items:center; gap:2rem;">
            <div>
                <div style="font-size:12px; color:var(--text-3);">Kids (50% off)</div>
                <div style="display:flex; align-items:center; gap:8px; margin-top:4px;">
                    <button onclick="changeKids(-1)" style="width:28px;height:28px;background:var(--surface-3);border:1px solid var(--border-2);border-radius:5px;color:#fff;font-size:16px;cursor:pointer;display:flex;align-items:center;justify-content:center;">−</button>
                    <span id="kidsCount" style="font-size:16px;font-weight:700;color:#fff;min-width:20px;text-align:center;">0</span>
                    <button onclick="changeKids(1)" style="width:28px;height:28px;background:var(--surface-3);border:1px solid var(--border-2);border-radius:5px;color:#fff;font-size:16px;cursor:pointer;display:flex;align-items:center;justify-content:center;">+</button>
                </div>
            </div>
            <div>
                <div style="font-size:12px; color:var(--text-3);">Total Amount</div>
                <div id="totalDisplay" style="font-size:26px; font-weight:900; color:var(--orange); line-height:1; margin-top:4px;">Rs. 0</div>
            </div>
            <form id="bookingForm" method="POST" action="{{ route('booking.summary') }}">
                @csrf
                <input type="hidden" name="show_id" value="{{ $show->id }}">
                <input type="hidden" name="seat_numbers" id="seatNumbersInput">
                <input type="hidden" name="seat_class" id="seatClassInput">
                <input type="hidden" name="kids_count" id="kidsInput" value="0">
                <button type="submit" id="proceedBtn" disabled
                    style="background:var(--red);color:#fff;padding:13px 28px;border-radius:8px;font-size:15px;font-weight:700;border:none;cursor:not-allowed;opacity:.4;transition:all .25s;font-family:var(--font-body);">
                    Proceed to Payment →
                </button>
            </form>
        </div>
    </div>

</div>

{{-- Pass PHP data to JS --}}
<script>
var BOOKED_SEATS  = @json($bookedSeats);
var SHOW_PRICES   = {
    gold:     {{ $show->gold_price }},
    platinum: {{ $show->platinum_price }},
    box:      {{ $show->box_price }}
};
</script>

@push('scripts')
<script>
// ============================================================
// CINEX SEAT MAP — Full Cinema Hall 12 rows × 14 seats
// Rows A-B = Box, C-E = Platinum, F-L = Gold
// Aisle between col 7 and 8
// ============================================================

var ROWS = ['A','B','C','D','E','F','G','H','I','J','K','L'];
var COLS = 14;
var AISLE_AFTER = 7;
var selected = {};
var kidsCount = 0;

function getClass(rowIdx) {
    if (rowIdx <= 1) return 'box';
    if (rowIdx <= 4) return 'platinum';
    return 'gold';
}

var CLASS_COLORS = {
    gold:     { bg:'#1a1000', border:'#633806', hoverBg:'#2d1a00', hoverBorder:'#EF9F27' },
    platinum: { bg:'#00101a', border:'#0c447c', hoverBg:'#001828', hoverBorder:'#378ADD' },
    box:      { bg:'#100010', border:'#3C3489', hoverBg:'#1a0028', hoverBorder:'#7F77DD' },
};

function buildHall() {
    var hall = document.getElementById('seatHall');
    var html = '';

    ROWS.forEach(function(row, ri) {
        // Class label row
        if (ri === 0) html += '<div style="text-align:center;font-size:10px;font-weight:700;color:#7F77DD;letter-spacing:.12em;text-transform:uppercase;margin-bottom:6px;padding-left:26px;">BOX CLASS</div>';
        if (ri === 2) html += '<div style="text-align:center;font-size:10px;font-weight:700;color:#378ADD;letter-spacing:.12em;text-transform:uppercase;margin:8px 0 6px;padding-left:26px;">PLATINUM CLASS</div>';
        if (ri === 5) html += '<div style="text-align:center;font-size:10px;font-weight:700;color:#EF9F27;letter-spacing:.12em;text-transform:uppercase;margin:8px 0 6px;padding-left:26px;">GOLD CLASS</div>';

        html += '<div style="display:flex;align-items:center;gap:5px;margin-bottom:5px;">';
        // Row label
        html += '<div style="width:18px;font-size:10px;color:#444;font-family:monospace;text-align:center;flex-shrink:0;">' + row + '</div>';

        for (var c = 1; c <= COLS; c++) {
            // Aisle gap
            if (c === AISLE_AFTER + 1) {
                html += '<div style="width:14px;flex-shrink:0;"></div>';
            }
            var seatId  = row + c;
            var cls     = getClass(ri);
            var isBooked = BOOKED_SEATS.indexOf(seatId) !== -1;
            var color   = CLASS_COLORS[cls];
            var bookedAttr = isBooked ? 'data-booked="1"' : '';

            html += '<div class="cx-seat" data-id="'+seatId+'" data-class="'+cls+'" data-price="'+SHOW_PRICES[cls]+'" '+bookedAttr+
                    ' style="width:24px;height:22px;border-radius:4px 4px 2px 2px;border:1px solid '+(isBooked?'#2a2a2a':color.border)+
                    ';background:'+(isBooked?'rgba(30,30,30,.35)':color.bg)+
                    ';cursor:'+(isBooked?'not-allowed':'pointer')+
                    ';transition:transform .1s,background .15s,border-color .15s;flex-shrink:0;position:relative;" '+
                    'title="'+seatId+(isBooked?' (Booked)':'')+'"'+
                    '></div>';
        }
        html += '</div>';
    });

    hall.innerHTML = html;

    // Attach events
    document.querySelectorAll('.cx-seat:not([data-booked])').forEach(function(seat) {
        var cls   = seat.dataset.class;
        var color = CLASS_COLORS[cls];

        seat.addEventListener('mouseenter', function() {
            if (!selected[seat.dataset.id]) {
                seat.style.background   = color.hoverBg;
                seat.style.borderColor  = color.hoverBorder;
                seat.style.transform    = 'scale(1.18)';
            }
        });
        seat.addEventListener('mouseleave', function() {
            if (!selected[seat.dataset.id]) {
                seat.style.background  = color.bg;
                seat.style.borderColor = color.border;
                seat.style.transform   = 'scale(1)';
            }
        });
        seat.addEventListener('click', function(e) {
               e.stopPropagation();
            if (seat.dataset.booked) return;
            toggleSeat(seat);
       });
    });
}

function toggleSeat(seat) {
    var id    = seat.dataset.id;
    var cls   = seat.dataset.class;
    var color = CLASS_COLORS[cls];

    if (selected.hasOwnProperty(id)) {
        delete selected[id];
        seat.style.background  = color.bg;
        seat.style.borderColor = color.border;
        seat.style.transform   = 'scale(1)';
        seat.style.boxShadow   = 'none';
        seat.setAttribute('data-selected', '0');
    } else {
        selected[id] = { cls: cls, price: parseFloat(seat.dataset.price) };
        seat.style.background  = '#d32f23';
        seat.style.borderColor = '#ff5544';
        seat.style.transform   = 'scale(1.1)';
        seat.style.boxShadow   = '0 0 10px rgba(211,47,35,.6)';
        seat.setAttribute('data-selected', '1');
    }
    updateSummary();
}

function changeKids(delta) {
    var total = Object.keys(selected).length;
    kidsCount = Math.max(0, Math.min(total, kidsCount + delta));
    document.getElementById('kidsCount').textContent = kidsCount;
    document.getElementById('kidsInput').value = kidsCount;
    updateSummary();
}

function updateSummary() {
    var seats    = Object.keys(selected);
    var numSeats = seats.length;
    var bar      = document.getElementById('summaryBar');
    var btn      = document.getElementById('proceedBtn');

    if (numSeats === 0) {
        bar.style.transform = 'translateY(100%)';
        btn.disabled = true; btn.style.opacity = '.4'; btn.style.cursor = 'not-allowed';
        return;
    }
    bar.style.transform = 'translateY(0)';

    // Detect dominant class (most selected)
    var classCounts = { gold:0, platinum:0, box:0 };
    var totalBase   = 0;
    seats.forEach(function(id) {
        classCounts[selected[id].cls]++;
        totalBase += selected[id].price;
    });
    var dominantClass = Object.keys(classCounts).reduce(function(a,b){ return classCounts[a]>classCounts[b]?a:b; });

    // Kids discount
    var kidsDiscount = kidsCount * (SHOW_PRICES[dominantClass] * 0.5);
    var total        = totalBase - kidsDiscount;

    // Update UI
    document.getElementById('selectedDisplay').textContent = seats.join(', ');
    document.getElementById('totalDisplay').textContent    = 'Rs. ' + total.toLocaleString();
    document.getElementById('seatNumbersInput').value      = seats.join(',');
    document.getElementById('seatClassInput').value        = dominantClass;
    document.getElementById('kidsInput').value             = kidsCount;

    // Enable button
    btn.disabled = false; btn.style.opacity = '1'; btn.style.cursor = 'pointer';

    // Max kids = num seats
    if (kidsCount > numSeats) {
        kidsCount = numSeats;
        document.getElementById('kidsCount').textContent = kidsCount;
    }
}

// Build on load
buildHall();
</script>
@endpush
@endsection